-- THIS TABLE IS USED TO NOT LOSE ASYNC EVENTS.
CREATE TABLE outbox_events(
    id UUID PRIMARY KEY DEFAULT uuidv7(),
    aggregate_id UUID NOT NULL, -- ENTITY ID (TRANSACTION_ID, ACCOUNT_ID)
    aggregate_type VARCHAR NOT NULL, -- ENTITY NAME (TRANSACTION, ACCOUNT)
    event_type VARCHAR NOT NULL, -- SEMANTIC TYPE OF THE EVENT (TRANSACTION_COMPLETED, TRANSACTION_FAILED, ACCOUNT_FROZEN)
    payload JSONB NOT NULL, -- RABBIT PAYLOAD
    status VARCHAR NOT NULL DEFAULT 'PENDING', -- STATUS OF THE EVENT ITSELF (PENDING, PROCESSED, DEAD)
    retry_count INTEGER NOT NULL DEFAULT 0, -- HOW MANY TIMES IT RETRIED
    exchange VARCHAR NOT NULL, -- WHICH RABBIT EXCHANGE PUBLISH THE MESSAGE
    routing_key VARCHAR NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    processed_at TIMESTAMP -- WHEN THE ACK IS RECEIVED FROM RABBIT
);

CREATE INDEX idx_outbox_status_created_at ON outbox_events (status, created_at);
CREATE INDEX idx_outbox_aggregate_id ON outbox_events (aggregate_id);